# Generated by Django 3.2.7 on 2021-09-30 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasureUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("abbreviation", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_item", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("description", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="")),
                (
                    "id_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_actual", models.IntegerField()),
                (
                    "id_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.item"
                    ),
                ),
            ],
        ),
    ]
