# Generated by Django 3.2.5 on 2021-11-25 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_item_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id_item',
        ),
    ]
