# Generated by Django 3.2.5 on 2021-11-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_item_sku'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeasureUnit',
        ),
    ]
