# Generated by Django 3.2.5 on 2021-11-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_delete_measureunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sku',
        ),
        migrations.AddField(
            model_name='item',
            name='stock_actual',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
